'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line } from 'recharts'
import { Download, FileText, Share2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { 
  handleExportReport, 
  handleDownloadReport 
} from '@/lib/button-handlers'

// Mock data
const sentimentData = [
  { name: 'Mon', positive: 65, neutral: 25, negative: 10 },
  { name: 'Tue', positive: 70, neutral: 20, negative: 10 },
  { name: 'Wed', positive: 60, neutral: 30, negative: 10 },
  { name: 'Thu', positive: 75, neutral: 15, negative: 10 },
  { name: 'Fri', positive: 80, neutral: 15, negative: 5 },
  { name: 'Sat', positive: 70, neutral: 20, negative: 10 },
  { name: 'Sun', positive: 75, neutral: 18, negative: 7 },
]

const sovData = [
  { name: 'Zenith', value: 45 },
  { name: 'GTBank', value: 30 },
  { name: 'Access', value: 15 },
  { name: 'Others', value: 10 },
]

const mentionsData = [
  { id: 1, title: 'Zenith Bank launches new digital initiative', source: 'Vanguard News', sentiment: 'positive', date: '2024-03-20', reach: '125K' },
  { id: 2, title: 'Customer complaints on mobile app downtime', source: 'Twitter', sentiment: 'negative', date: '2024-03-19', reach: '45K' },
  { id: 3, title: 'Zenith Bank reports strong Q1 earnings', source: 'BusinessDay', sentiment: 'positive', date: '2024-03-18', reach: '89K' },
  { id: 4, title: 'Industry analysis: Banking sector outlook', source: 'LinkedIn', sentiment: 'neutral', date: '2024-03-17', reach: '32K' },
  { id: 5, title: 'Zenith Bank wins award for innovation', source: 'Premium Times', sentiment: 'positive', date: '2024-03-16', reach: '67K' },
]

export default function DashboardPage() {
  const router = useRouter()
  const [isExporting, setIsExporting] = useState(false)

  const getSentimentColor = (sentiment: string) => {
    switch (sentiment) {
      case 'positive': return 'text-green-500 bg-green-500/10 border-green-500/20'
      case 'negative': return 'text-red-500 bg-red-500/10 border-red-500/20'
      default: return 'text-gray-500 bg-gray-500/10 border-gray-500/20'
    }
  }

  const handleExportPDF = async () => {
    setIsExporting(true)
    try {
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 1500))
      
      // Create a simple text report for demo
      const reportContent = `
INTELLIGENCE REPORT
Generated: ${new Date().toLocaleDateString()}

KEY METRICS:
- Total Reach: 1.2M
- Sentiment: 72% Positive
- SOV: 45%

TOP MENTIONS:
${mentionsData.map(m => `- ${m.title} (${m.sentiment})`).join('\n')}

---
Generated by Flash Narrative
      `.trim()

      const blob = new Blob([reportContent], { type: 'text/plain' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `intelligence-report-${new Date().toISOString().split('T')[0]}.txt`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
      
    } catch (error) {
      console.error('Failed to export PDF:', error)
      alert('Failed to generate report. Please try again.')
    } finally {
      setIsExporting(false)
    }
  }

  const handleExportExcel = async () => {
    setIsExporting(true)
    try {
      await new Promise(resolve => setTimeout(resolve, 1500))
      
      // Create CSV content
      const csvContent = "data:text/csv;charset=utf-8," 
        + "Title,Source,Sentiment,Date,Reach\n"
        + mentionsData.map(m => `"${m.title}","${m.source}","${m.sentiment}","${m.date}","${m.reach}"`).join("\n")

      const encodedUri = encodeURI(csvContent)
      const link = document.createElement("a")
      link.setAttribute("href", encodedUri)
      link.setAttribute("download", `mentions-data-${new Date().toISOString().split('T')[0]}.csv`)
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      
    } catch (error) {
      console.error('Failed to export Excel:', error)
      alert('Failed to generate Excel file. Please try again.')
    } finally {
      setIsExporting(false)
    }
  }

  return (
    <div className="space-y-6">
      {/* Header Actions */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-white">Intelligence Dashboard</h1>
          <p className="text-muted-foreground mt-1">
            Real-time brand narrative tracking and analysis
          </p>
        </div>
        <div className="flex gap-2">
          <Button 
            variant="outline" 
            onClick={handleExportExcel}
            disabled={isExporting}
            className="border-amber-500/30 text-amber-500 hover:bg-amber-500/10"
          >
            <FileText className="w-4 h-4 mr-2" />
            {isExporting ? 'Exporting...' : 'Export Excel'}
          </Button>
          <Button 
            onClick={handleExportPDF}
            disabled={isExporting}
            className="bg-gradient-to-r from-amber-600 to-amber-700 hover:from-amber-700 hover:to-amber-800"
          >
            <Download className="w-4 h-4 mr-2" />
            {isExporting ? 'Generating...' : 'Export PDF'}
          </Button>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card className="border-white/5 bg-black/20">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Total Reach
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-white">1.2M</div>
            <p className="text-xs text-green-500 mt-1">+18% from last week</p>
          </CardContent>
        </Card>
        <Card className="border-white/5 bg-black/20">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Positive Sentiment
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-white">72%</div>
            <p className="text-xs text-green-500 mt-1">+5% from last week</p>
          </CardContent>
        </Card>
        <Card className="border-white/5 bg-black/20">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Share of Voice
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-white">45%</div>
            <p className="text-xs text-red-500 mt-1">-2% from last week</p>
          </CardContent>
        </Card>
        <Card className="border-white/5 bg-black/20">
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium text-muted-foreground">
              Crisis Alerts
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-white">3</div>
            <p className="text-xs text-muted-foreground mt-1">Active alerts</p>
          </CardContent>
        </Card>
      </div>

      {/* Charts Row */}
      <div className="grid gap-4 md:grid-cols-2">
        <Card className="border-white/5 bg-black/20">
          <CardHeader>
            <CardTitle className="text-white">Sentiment Trend</CardTitle>
            <CardDescription>Daily sentiment distribution over the last 7 days</CardDescription>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={300}>
              <BarChart data={sentimentData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#333" />
                <XAxis dataKey="name" stroke="#666" />
                <YAxis stroke="#666" />
                <Tooltip 
                  contentStyle={{ backgroundColor: '#0A0A0A', borderColor: '#333', color: '#fff' }}
                />
                <Bar dataKey="positive" fill="#22c55e" stackId="a" />
                <Bar dataKey="neutral" fill="#666" stackId="a" />
                <Bar dataKey="negative" fill="#ef4444" stackId="a" />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        <Card className="border-white/5 bg-black/20">
          <CardHeader>
            <CardTitle className="text-white">Share of Voice</CardTitle>
            <CardDescription>Brand visibility compared to competitors</CardDescription>
          </CardHeader>
          <CardContent>
            <ResponsiveContainer width="100%" height={300}>
              <BarChart data={sovData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#333" />
                <XAxis dataKey="name" stroke="#666" />
                <YAxis stroke="#666" />
                <Tooltip 
                  contentStyle={{ backgroundColor: '#0A0A0A', borderColor: '#333', color: '#fff' }}
                />
                <Bar dataKey="value" fill="#f59e0b" />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>
      </div>

      {/* Recent Mentions Table */}
      <Card className="border-white/5 bg-black/20">
        <CardHeader>
          <div className="flex justify-between items-center">
            <div>
              <CardTitle className="text-white">Recent Mentions</CardTitle>
              <CardDescription>Latest brand mentions across all channels</CardDescription>
            </div>
            <Button variant="outline" className="border-amber-500/30 text-amber-500 hover:bg-amber-500/10">
              View All
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-white/5">
                  <th className="text-left py-3 px-4 text-sm font-medium text-muted-foreground">Title</th>
                  <th className="text-left py-3 px-4 text-sm font-medium text-muted-foreground">Source</th>
                  <th className="text-left py-3 px-4 text-sm font-medium text-muted-foreground">Sentiment</th>
                  <th className="text-left py-3 px-4 text-sm font-medium text-muted-foreground">Date</th>
                  <th className="text-left py-3 px-4 text-sm font-medium text-muted-foreground">Reach</th>
                  <th className="text-right py-3 px-4 text-sm font-medium text-muted-foreground">Actions</th>
                </tr>
              </thead>
              <tbody>
                {mentionsData.map((mention) => (
                  <tr key={mention.id} className="border-b border-white/5 hover:bg-white/5 transition-colors">
                    <td className="py-3 px-4 text-sm text-white max-w-xs truncate">{mention.title}</td>
                    <td className="py-3 px-4 text-sm text-muted-foreground">{mention.source}</td>
                    <td className="py-3 px-4">
                      <Badge className={`text-xs ${getSentimentColor(mention.sentiment)}`}>
                        {mention.sentiment}
                      </Badge>
                    </td>
                    <td className="py-3 px-4 text-sm text-muted-foreground">{mention.date}</td>
                    <td className="py-3 px-4 text-sm text-white font-medium">{mention.reach}</td>
                    <td className="py-3 px-4 text-right">
                      <Button variant="ghost" size="sm" className="text-muted-foreground hover:text-white">
                        <Share2 className="w-4 h-4" />
                      </Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
